### ISSUE TITLE
Uncaught Error: Unable to start terminal process: CreateProcess failed

### ISSUE THREAD

**Issue by noyobo** [Microsoft/node-pty#197] opened 2018-05-23 14:58 UTC
## Environment details

- OS:  windows 7 X64
- OS version: 
- node-pty version:  0.7.4

## Issue description

Under `example/electron` direct execution `npm` error, but work on OSX.

**error**

```
Uncaught Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\workspace\node-pty\examples\electron\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\workspace\node-pty\examples\electron\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at Object.spawn (C:\workspace\node-pty\examples\electron\node_modules\node-/pty\lib\index.js:27:12)
    at Object.<anonymous> (C:\workspace\node-pty\examples\electron\renderer.js:5:24)
    at Object.<anonymous> (C:\workspace\node-pty\examples\electron\renderer.js:25:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

```js
// renderer.js
var os = require('os');
var pty = require('node-pty');
var Terminal = require('xterm').Terminal;

const ptyProcess = pty.spawn('npm', ['-v'], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.cwd(),
  env: process.env
});

// Initialize xterm.js and attach it to the DOM
const xterm = new Terminal();
xterm.open(document.getElementById('xterm'));

// Setup communication between xterm.js and node-pty
xterm.on('data', (data) => {
  ptyProcess.write(data);
});
ptyProcess.on('data', function (data) {
  xterm.write(data);
});
```

**Comment by Tyriar** [comment] 2018-05-23 18:33
This could be related to https://github.com/Microsoft/vscode/issues/43169

**Comment by noyobo** [comment] 2018-05-24 03:31
Provide an absolute path `c:/xx/xx/npm.cmd` can resovle this problem 

```js
// renderer.js
var os = require('os');
var pty = require('node-pty');
var Terminal = require('xterm').Terminal;

const ptyProcess = pty.spawn('c:/xx/xx/npm.cmd', ['-v'], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.cwd(),
  env: process.env
});

// Initialize xterm.js and attach it to the DOM
const xterm = new Terminal();
xterm.open(document.getElementById('xterm'));

// Setup communication between xterm.js and node-pty
xterm.on('data', (data) => {
  ptyProcess.write(data);
});
ptyProcess.on('data', function (data) {
  xterm.write(data);
});
```

**Comment by Tyriar** [comment] 2018-05-24 15:08
Ah, this is a duplicate of https://github.com/Microsoft/node-pty/issues/112

**Closed by Tyriar** 2018-05-24 15:08 UTC
Labels: bug, help wanted
