### ISSUE TITLE
Windows cmd.exe execution bug

### ISSUE THREAD

**Issue by Squitch1** [Microsoft/node-pty#502] opened 2021-10-20 17:01 UTC
## Environment details

- OS: Windows
- OS version: 19043.1288
- node-pty version: 0.10.1

## Issue description
When trying to run `cmd.exe`, It crashes randomly with this error:
![image](https://user-images.githubusercontent.com/63391793/138138019-b598edda-1702-4930-812b-1d0db31caee7.png)
But with the full path no error.
The path where is `cmd.exe` is in my Env Variables

**Comment by Tyriar** [comment] 2021-10-21 19:48
duplicate of #112

**Closed as completed by Tyriar** 2021-10-21 19:48 UTC
Labels: duplicate
