### ISSUE TITLE
Provide a pre-gyp build for windows.

### ISSUE THREAD

**Issue by Kreijstal** [microsoft/node-pty#449] opened 2021-01-07 11:02 UTC
So that you can install it using npm when you don't want or can't install the compilers just to use the library, but you want to use the library already build.
This has the added benefit that you could use this package when you run a machine without privileges otherwise this package is impossible to use.

**Comment by Tyriar** [comment] 2021-01-07 14:29
duplicate of https://github.com/microsoft/node-pty/issues/46

**Closed by Tyriar** 2021-01-07 14:29 UTC
