### ISSUE TITLE
term.kill can't kill setuid process.

### ISSUE THREAD

**Issue by hezedu** [microsoft/node-pty#393] opened 2020-03-30 03:49 UTC
## Environment details

- OS: linux
- OS version: ubuntu 16.04
- node-pty version: 0.9.0

## Issue description
https://github.com/microsoft/node-pty/blob/44c53768777263d9cde78b0ac2d1f7c6338d4131/src/unixTerminal.ts#L243-L247
node-pty used process.kill to kill term's process. It can't kill some special process (eg: bin shell is setuid(0));
### demo
https://github.com/hezedu/SomethingBoring/tree/master/issue/node-pty/kill
### How did I solve it?
```js
term.write('\u0003'); // Ctrl + C
```

**Comment by Tyriar** [comment] 2020-04-05 16:33
@jerch maybe you know if this is a trivial fix? I'm not familiar with how setuid works.

**Comment by jerch** [comment] 2020-04-05 18:13
Hmm not sure, @hezedu are we talking about `setsid` or really `setuid(0)`? The latter is supposed not to work from an unprivileged process, otherwise anyone could kill root processes anytime.

So if you are doing `setuid(0)` you tell the system to run the shell as root process, now if node-pty runs in a non-root process, it cannot kill that process. Its not a bug, its a feature :smiley_cat:

**Comment by hezedu** [comment] 2020-04-06 09:45
OK. This is no problem.
When you are an normal user:
I think porcess.kill can't kill other user process. whether it's root process or not. 
I think if you use process.exit() you can kill root term and kill root process.

How about kill term by disconnecting the socket?

**Comment by jerch** [comment] 2020-04-06 11:50
@hezedu:
Yes, you can "kill" a root process on a terminal by "closing" the terminal. What happens in the background:
From OS viewpoint a PTY is just a pipe with a master and a slave endpoint. The master is meant for a process mimicking the terminal, the slave endpoint is where processes running on that "terminal" get attached to. `node-pty` provides access to the master end by its data event and `write` method, the slave end is not held by `node-pty`.

Now if you close the master end, the pipe gets dysfunctional, thus the kernel (TTY driver) would initiate a `SIGHUP` to the slave side - the process will end (if it does not block `SIGHUP`).

**Closed** 2020-04-06 11:52 UTC
Labels: question
