### ISSUE TITLE
install error with MSB5010

### ISSUE THREAD

**Issue by lxxxl123** [microsoft/node-pty#572] opened 2022-12-15 08:33 UTC
## Environment details
- OS: win10
- OS version: 19044.1288
- node-pty version: 0.10
- node: 16.19 and 17.9
- gyp: 9.x and 8.x
- msVersion: 2022 and 2017
- python: 3.8 , 3.9 , 3.10

## Issue description
i try to install 0.9 , 0.10 , 0.11 , but it occur error . 
```
$ npm i node-pty
npm ERR! code 1
npm ERR! path D:\workspace-new\temp\node_modules\node-pty
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
npm ERR! D:\workspace-new\temp\node_modules\node-pty\build\binding.sln : 解决方案文件 error MSB5010: 未找到文件格式头。(No file format header found)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@16.19.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.9 found at "C:\Users\chenwh3\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.33027.88) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\chenwh3\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\workspace-new\\temp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\workspace-new\\temp\\node_modules\\node-pty\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\workspace-new\\temp\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\chenwh3\\AppData\\Local\\node-gyp\\Cache\\16.19.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\chenwh3\\AppData\\Local\\node-gyp\\Cache\\16.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\workspace-new\\temp\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\chenwh3\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.19.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\workspace-new\\temp\\node_modules\\node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\workspace-new\\temp\\node_modules\\node-pty\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (D:\workspace-new\temp\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\workspace-new\\temp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\workspace-new\temp\node_modules\node-pty
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chenwh3\AppData\Local\npm-cache\_logs\2022-12-15T08_11_32_922Z-debug-0.log

```

**Comment by Tyriar** [comment] 2022-12-16 16:26
duplicate of https://github.com/microsoft/node-pty/issues/438

**Closed by Tyriar** 2022-12-16 16:26 UTC
