### ISSUE TITLE
Open Terminal in vscode is broken

### ISSUE THREAD

**Issue by lioramilbaum** [microsoft/node-pty#458] opened 2021-02-09 09:55 UTC
## Environment details

- OS: RHEL
- OS version: 7.9
- node-pty version: 1.53.0

## Issue description

![Screenshot from 2021-02-09 11-53-31](https://user-images.githubusercontent.com/7271026/107346631-98d70380-6acd-11eb-895f-4f3a50789b14.png)

**Comment by Tyriar** [comment] 2021-02-09 13:21
Duplicate of https://github.com/microsoft/vscode/issues/115784

**Closed by Tyriar** 2021-02-09 13:21 UTC
