### ISSUE TITLE
Interface IPty does not reflect actual object

### ISSUE THREAD

**Issue by bluebrown** [microsoft/node-pty#409] opened 2020-05-23 17:25 UTC
## Environment details

- OS: CentOS
- OS version: 8
- node-pty version: 0.9.0

## Issue description

The below code works actually when using vanilla JavaScript. However, when I want to use it in typescript I get an error.

```
const proc = require('node-pty').spawn(cmd, args, opts);
require('stream').pipeline(proc, process.stdout, errorHanlder);
```

Error: 

```
Argument of type 'IPty' is not assignable to parameter of type 'ReadableStream'.ts(2769)
```

**Comment by jerch** [comment] 2020-05-23 23:24
@bluebrown This looks like an inconsistency of the declared TS interfaces on both ends. Can you elaborate on what differs between them?

**Comment by bluebrown** [comment] 2020-05-24 21:36
Yes, it's an issue with the pipeline function being very nit picky. I have the problem with other things to that work in vanilla. For example piping an HTTP request object.

**Comment by bluebrown** [comment] 2020-05-24 21:39
Ah actually I just mistaken ReadStream with ReadableStream. HTTP request works.

**Comment by bluebrown** [comment] 2020-05-25 23:01
I think this one here is related.

The options comment for encoding tells us that we can pass a buffer. 

> String encoding of the underlying pty. If set, incoming data will be decoded to strings and outgoing strings to bytes applying this encoding. If unset, incoming data will be delivered as raw bytes (Buffer type). By default 'utf8' is assumed, to unset it explicitly set it to null.

The only function that could do this is the write function.  However, the typing of the write function dictates that only string can be passed as argument. In fact passing  a UInt8Array works just fine in vanilla.

I think this interface does not properly reflect what the object can actually do and how can be used. 

![image](https://user-images.githubusercontent.com/39703898/82847069-fa295900-9ee3-11ea-994b-35f34fff8a31.png)

**Comment by bluebrown** [comment] 2020-05-25 23:15
The same issue applies also on the 'outgoing stream' . I set encoding to null, so that the outgoing data will passed raw.  The function signature tells us that this function will always return a string.

![image](https://user-images.githubusercontent.com/39703898/82847410-debf4d80-9ee5-11ea-8568-9da7d4f76663.png)

**Comment by jerch** [comment] 2020-05-26 08:06
@bluebrown Imho `IPty` was never meant to be stream compatible, I am not even sure if that would be fully possible (mimicking the interface surely would, but still the semantics/behavior are way different). For example the unix variant uses internally a hack on the socket interface, which technically exposes the socket interface, but is unreliable. For Windows it is an aggregation either from WinPty or ConPty abstraction, where again certain things would work, others not. In this regard using the `IPty` directly on top of other proper stream interfaces is unsupported, thus use it only at your own risk.

What commonly gets used by implementations and is known to work:
- `spawn` call
- `write` with strings (assuming utf8)
- data event with strings (again assumes utf8)
- `resize` to announce size change to OS

Beside that, things get more wonky and will not work under certain circumstances:
- `pause` and `resume` - works reliably with blocking semantics from my own tests, if done after delivery started, but is wonky at the early stage (will swallow chunks, if a consumer happens to attach slowly)
- set encoding on both read and write - happens to work on most systems with the default of utf8, as kinda all systems are on utf8 these days, but switching to 8bit encoding (e.g. latin-1) does only work, if encoding is set to `null` (binary mode), as nodejs does not understand those other encodings. But switching into binary mode is not supported under Windows, thus cannot be offered globally.
- `kill` - most certainly works for the first process on slave side (session leader), but whether it also tries to kill children depends alot on underlying OS (POSIX will send a SIGHUP which bubbles, Windows cannot do that)
- `processname` - works for some OS, not implemented for others
- short running slave programs might exit early without delivering all chunks to the master side in time

So while `node-pty` gets the job done in a platform independent manner for the basics, it is quite bumpy for more specific ideas around a pty.

**Comment by Tyriar** [comment] 2020-05-26 14:19
Closing as designed for now.

**Closed by Tyriar** 2020-05-26 14:19 UTC
